# Generated by Django 5.1.1 on 2024-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
