    FROM python:3.13-alphine:3.21

    WORKDIR app/

    ENV PYTHONDONTWRITEBYTECODE 1 
    ENV PYTHONUNBUFFERED 1

    COPY SRC/. /req.txt /app/

    RUN pip install -U pip \
        pip install -r req.txt

    EXPOSE 8000

    CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]