# Generated by Django 5.1.1 on 2024-09-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/%y/%m/%d'),
        ),
    ]
